name: Helm Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: v3.14.3
      - run: helm lint ./helm/my-app
      - run: helm template ./helm/my-app --values ./helm/my-app/values.yaml
