name: Kubernetes Manifest Validation

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0
      - run: |
          kubectl apply --dry-run=client -f k8s/
