name: Train & Deploy on AWS SageMaker

on:
  workflow_dispatch:

jobs:
  sagemaker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Submit training job
        run: |
          aws sagemaker create-training-job \
            --training-job-name my-training-job \
            --algorithm-specification TrainingImage=my-image,TrainingInputMode=File \
            --input-data-config file://configs/input.json \
            --output-data-config S3OutputPath=s3://mybucket/output/ \
            --resource-config file://configs/resources.json \
            --role-arn ${{ secrets.AWS_SAGEMAKER_ROLE }}

      - name: Deploy model endpoint
        run: |
          aws sagemaker create-endpoint-config \
            --endpoint-config-name my-endpoint-config \
            --production-variants VariantName=AllTraffic,ModelName=my-model,InitialInstanceCount=1,InstanceType=ml.m5.large
          aws sagemaker create-endpoint --endpoint-name my-endpoint --endpoint-config-name my-endpoint-config
