name: Deploy MCP Server with Helm

on:
  push:
    branches: [ main ]

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.3

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config

      - name: Helm upgrade/install MCP
        run: |
          helm upgrade --install my-mcp-server ./helm/mcp \
            --namespace mcp \
            --create-namespace \
            --values ./helm/mcp/values.yaml
