name: Kaniko Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build with Kaniko
        uses: aevea/action-kaniko@v0.10.0
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
