name: Deploy MCP Server to GCP Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/my-mcp-server

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-mcp-server \
            --image gcr.io/$PROJECT_ID/my-mcp-server \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
